server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrespw
    url: jdbc:postgresql://localhost:55000/planner
  config:
    activate:
      on-profile: local
security:
  jwt:
    key: sharing_planner_secret_key
    minutes: 60
    domainUrl: sharing-planner.com
